version: '3.8'

services:
  db:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: data_engine_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=climate_data
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: data_engine_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  db_data:
